#!/usr/bin/env python3
import sys
import subprocess
import os
import fcntl
import base64
import logging
import ctypes
import ctypes.util
import time
from logging.handlers import RotatingFileHandler
from datetime import datetime

try:
    from PyQt5.QtWidgets import (QApplication, QWidget, QVBoxLayout, QSlider,
                                 QLabel, QSystemTrayIcon, QMenu, QCheckBox,
                                 QHBoxLayout, QComboBox, QPushButton)
    from PyQt5.QtGui import QIcon, QPixmap, QPainter, QColor, QFont, QCursor
    from PyQt5.QtCore import Qt, QObject, QTimer, QEvent
    QT_VERSION = 5

    _LEFT_BUTTON    = Qt.LeftButton
    _TRANSPARENT    = Qt.transparent
    _NO_PEN         = Qt.NoPen
    _ALIGN_CENTER   = Qt.AlignCenter
    _HORIZONTAL     = Qt.Horizontal
    _POPUP          = Qt.Tool
    _FRAMELESS      = Qt.FramelessWindowHint
    _STAYS_ON_TOP   = Qt.WindowStaysOnTopHint
    _TRAY_TRIGGER   = QSystemTrayIcon.Trigger
    _ANTIALIAS      = QPainter.Antialiasing
    _BOLD           = QFont.Bold
    _EXTRABOLD      = QFont.ExtraBold

except ImportError:
    from PyQt6.QtWidgets import (QApplication, QWidget, QVBoxLayout, QSlider,
                                 QLabel, QSystemTrayIcon, QMenu, QCheckBox,
                                 QHBoxLayout, QComboBox, QPushButton)
    from PyQt6.QtGui import QIcon, QPixmap, QPainter, QColor, QFont, QCursor
    from PyQt6.QtCore import Qt, QObject, QTimer, QEvent
    QT_VERSION = 6

    _LEFT_BUTTON    = Qt.MouseButton.LeftButton
    _TRANSPARENT    = Qt.GlobalColor.transparent
    _NO_PEN         = Qt.PenStyle.NoPen
    _ALIGN_CENTER   = Qt.AlignmentFlag.AlignCenter
    _HORIZONTAL     = Qt.Orientation.Horizontal
    _POPUP          = Qt.WindowType.Tool
    _FRAMELESS      = Qt.WindowType.FramelessWindowHint
    _STAYS_ON_TOP   = Qt.WindowType.WindowStaysOnTopHint
    _TRAY_TRIGGER   = QSystemTrayIcon.ActivationReason.Trigger
    _ANTIALIAS      = QPainter.RenderHint.Antialiasing
    _BOLD           = QFont.Weight.Bold
    _EXTRABOLD      = QFont.Weight.ExtraBold

# ---------------------------------------------------------------------------

ENGINE_B64 = "f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAwBcAAAAAAABAAAAAAAAAADBLAAAAAAAAAAAAAEAAOAANAEAAHwAeAAYAAAAEAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAA2AIAAAAAAADYAgAAAAAAAAgAAAAAAAAAAwAAAAQAAAAYAwAAAAAAABgDAAAAAAAAGAMAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAAAAAAAAABAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANgMAAAAAAAA2AwAAAAAAAAAEAAAAAAAAAEAAAAFAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAA5QgAAAAAAADlCAAAAAAAAAAQAAAAAAAAAQAAAAQAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAADoDgAAAAAAAOgOAAAAAAAAABAAAAAAAAABAAAABgAAAOA8AAAAAAAA4DwAAAAAAADgPAAAAAAAADADAAAAAAAAUAMAAAAAAAAAEAAAAAAAAAIAAAAGAAAA8DwAAAAAAADwPAAAAAAAAPA8AAAAAAAAIAIAAAAAAAAgAgAAAAAAAAgAAAAAAAAABAAAAAQAAAA4AwAAAAAAADgDAAAAAAAAOAMAAAAAAAAwAAAAAAAAADAAAAAAAAAACAAAAAAAAAAEAAAABAAAAGgDAAAAAAAAaAMAAAAAAABoAwAAAAAAAEQAAAAAAAAARAAAAAAAAAAEAAAAAAAAAFPldGQEAAAAOAMAAAAAAAA4AwAAAAAAADgDAAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAAC0LQAAAAAAALQtAAAAAAAAtC0AAAAAAAA8AAAAAAAAADwAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAA4DwAAAAAAADgPAAAAAAAAOA8AAAAAAAAIAMAAAAAAAAgAwAAAAAAAAEAAAAAAAAAL2xpYjY0L2xkLWxpbnV4LXg4Ni02NC5zby4yAAAAAAAEAAAAIAAAAAUAAABHTlUAAgAAwAQAAAADAAAAAAAAAAKAAMAEAAAAAQAAAAAAAAAEAAAAFAAAAAMAAABHTlUAKmW/bAbyoRdkri9PI/SI2b8zLVUEAAAAEAAAAAEAAABHTlUAAAAAAAMAAAACAAAAAAAAAAAAAAACAAAAGwAAAAEAAAAGAAAAAAGBAAAAAAIbAAAAHAAAANFlzm058oscAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2wEAABIAAAAAAAAAAAAAAAAAAAAAAAAAZgEAABIAAAAAAAAAAAAAAAAAAAAAAAAAVAAAABIAAAAAAAAAAAAAAAAAAAAAAAAAGwEAABIAAAAAAAAAAAAAAAAAAAAAAAAABAIAABIAAAAAAAAAAAAAAAAAAAAAAAAAHQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAEgIAABIAAAAAAAAAAAAAAAAAAAAAAAAAtwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAACAAAAAAAAAAAAAAAAAAAAAAAAAA9wAAABIAAAAAAAAAAAAAAAAAAAAAAAAAjgAAABIAAAAAAAAAAAAAAAAAAAAAAAAA8QEAABIAAAAAAAAAAAAAAAAAAAAAAAAALAAAACAAAAAAAAAAAAAAAAAAAAAAAAAARgAAABIAAAAAAAAAAAAAAAAAAAAAAAAAjQEAABIAAAAAAAAAAAAAAAAAAAAAAAAAwwAAABIAAAAAAAAAAAAAAAAAAAAAAAAA/QEAABIAAAAAAAAAAAAAAAAAAAAAAAAA4AEAABIAAAAAAAAAAAAAAAAAAAAAAAAASAEAABIAAAAAAAAAAAAAAAAAAAAAAAAAugEAABIAAAAAAAAAAAAAAAAAAAAAAAAAQQIAABIAAAAAAAAAAAAAAAAAAAAAAAAAfAAAABIAAAAAAAAAAAAAAAAAAAAAAAAApwAAABIAAAAAAAAAAAAAAAAAAAAAAAAAbQAAABIAAAAAAAAAAAAAAAAAAAAAAAAAGQIAABIAAAAAAAAAAAAAAAAAAAAAAAAA9gEAABIAAAAAAAAAAAAAAAAAAAAAAAAAMgIAACIAAAAAAAAAAAAAAAAAAAAAAAAAKwIAABEAGgAgQAAAAAAAAAgAAAAAAAAAAF9JVE1fZGVyZWdpc3RlclRNQ2xvbmVUYWJsZQBfX2dtb25fc3RhcnRfXwBfSVRNX3JlZ2lzdGVyVE1DbG9uZVRhYmxlAHhjYl9nZXRfc2V0dXAAeGNiX2Nvbm5lY3Rpb25faGFzX2Vycm9yAHhjYl9kaXNjb25uZWN0AHhjYl9yZXF1ZXN0X2NoZWNrAHhjYl9zZXR1cF9yb290c19pdGVyYXRvcgB4Y2Jfc2NyZWVuX25leHQAeGNiX2Nvbm5lY3QAeGNiX3JhbmRyX2dldF9zY3JlZW5fcmVzb3VyY2VzX2N1cnJlbnRfY3J0Y3NfbGVuZ3RoAHhjYl9yYW5kcl9nZXRfY3J0Y19nYW1tYV9zaXplX3JlcGx5AHhjYl9yYW5kcl9nZXRfc2NyZWVuX3Jlc291cmNlc19jdXJyZW50X2NydGNzAHhjYl9yYW5kcl9nZXRfY3J0Y19nYW1tYV9zaXplAHhjYl9yYW5kcl9nZXRfc2NyZWVuX3Jlc291cmNlc19jdXJyZW50AHhjYl9yYW5kcl9nZXRfc2NyZWVuX3Jlc291cmNlc19jdXJyZW50X3JlcGx5AHhjYl9yYW5kcl9zZXRfY3J0Y19nYW1tYV9jaGVja2VkAHBvd2YAX19zdGFja19jaGtfZmFpbABmcmVlAHN0cnRvZABzdHJ0b2wAX19mcHJpbnRmX2NoawBtYWxsb2MAX19saWJjX3N0YXJ0X21haW4Ac3RkZXJyAF9fY3hhX2ZpbmFsaXplAGNhbGxvYwBsaWJ4Y2Iuc28uMQBsaWJ4Y2ItcmFuZHIuc28uMABsaWJtLnNvLjYAbGliYy5zby42AEdMSUJDXzIuMzQAR0xJQkNfMi40AEdMSUJDXzIuMi41AEdMSUJDXzIuMy40AEdMSUJDXzIuMjcAAAACAAEAAQABAAMAAQAEAAEAAQABAAEABAABAAEAAQABAAQABQABAAEABAABAAEAAQAGAAQABAAEAAAAAAABAAQAcAIAABAAAABQAAAAtJGWBgAABgB6AgAAEAAAABRpaQ0AAAUAhQIAABAAAAB1GmkJAAAEAI8CAAAQAAAAdBlpCQAAAwCbAgAAAAAAAAEAAQBmAgAAEAAAAAAAAACHkZYGAAACAKcCAAAAAAAA4DwAAAAAAAAIAAAAAAAAAKAYAAAAAAAA6DwAAAAAAAAIAAAAAAAAAGAYAAAAAAAACEAAAAAAAAAIAAAAAAAAAAhAAAAAAAAA2D8AAAAAAAAGAAAABgAAAAAAAAAAAAAA4D8AAAAAAAAGAAAACQAAAAAAAAAAAAAA6D8AAAAAAAAGAAAADQAAAAAAAAAAAAAA8D8AAAAAAAAGAAAAGwAAAAAAAAAAAAAA+D8AAAAAAAAGAAAAGQAAAAAAAAAAAAAAIEAAAAAAAAAFAAAAHAAAAAAAAAAAAAAAKD8AAAAAAAAHAAAAAQAAAAAAAAAAAAAAMD8AAAAAAAAHAAAAAgAAAAAAAAAAAAAAOD8AAAAAAAAHAAAAAwAAAAAAAAAAAAAAQD8AAAAAAAAHAAAABAAAAAAAAAAAAAAASD8AAAAAAAAHAAAABQAAAAAAAAAAAAAAUD8AAAAAAAAHAAAABwAAAAAAAAAAAAAAWD8AAAAAAAAHAAAACAAAAAAAAAAAAAAAYD8AAAAAAAAHAAAACgAAAAAAAAAAAAAAaD8AAAAAAAAHAAAACwAAAAAAAAAAAAAAcD8AAAAAAAAHAAAADAAAAAAAAAAAAAAAeD8AAAAAAAAHAAAADgAAAAAAAAAAAAAAgD8AAAAAAAAHAAAADwAAAAAAAAAAAAAAiD8AAAAAAAAHAAAAEAAAAAAAAAAAAAAAkD8AAAAAAAAHAAAAEQAAAAAAAAAAAAAAmD8AAAAAAAAHAAAAEgAAAAAAAAAAAAAAoD8AAAAAAAAHAAAAEwAAAAAAAAAAAAAAqD8AAAAAAAAHAAAAFAAAAAAAAAAAAAAAsD8AAAAAAAAHAAAAFQAAAAAAAAAAAAAAuD8AAAAAAAAHAAAAFgAAAAAAAAAAAAAAwD8AAAAAAAAHAAAAFwAAAAAAAAAAAAAAyD8AAAAAAAAHAAAAGAAAAAAAAAAAAAAA0D8AAAAAAAAHAAAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPMPHvpIg+wISIsFyS8AAEiFwHQC/9BIg8QIwwAAAAAA/zXyLgAA/yX0LgAADx9AAPMPHvpoAAAAAOni////ZpDzDx76aAEAAADp0v///2aQ8w8e+mgCAAAA6cL///9mkPMPHvpoAwAAAOmy////ZpDzDx76aAQAAADpov///2aQ8w8e+mgFAAAA6ZL///9mkPMPHvpoBgAAAOmC////ZpDzDx76aAcAAADpcv///2aQ8w8e+mgIAAAA6WL///9mkPMPHvpoCQAAAOlS////ZpDzDx76aAoAAADpQv///2aQ8w8e+mgLAAAA6TL///9mkPMPHvpoDAAAAOki////ZpDzDx76aA0AAADpEv///2aQ8w8e+mgOAAAA6QL///9mkPMPHvpoDwAAAOny/v//ZpDzDx76aBAAAADp4v7//2aQ8w8e+mgRAAAA6dL+//9mkPMPHvpoEgAAAOnC/v//ZpDzDx76aBMAAADpsv7//2aQ8w8e+mgUAAAA6aL+//9mkPMPHvpoFQAAAOmS/v//ZpDzDx76/yVWLgAAZg8fRAAA8w8e+v8lfi0AAGYPH0QAAPMPHvr/JXYtAABmDx9EAADzDx76/yVuLQAAZg8fRAAA8w8e+v8lZi0AAGYPH0QAAPMPHvr/JV4tAABmDx9EAADzDx76/yVWLQAAZg8fRAAA8w8e+v8lTi0AAGYPH0QAAPMPHvr/JUYtAABmDx9EAADzDx76/yU+LQAAZg8fRAAA8w8e+v8lNi0AAGYPH0QAAPMPHvr/JS4tAABmDx9EAADzDx76/yUmLQAAZg8fRAAA8w8e+v8lHi0AAGYPH0QAAPMPHvr/JRYtAABmDx9EAADzDx76/yUOLQAAZg8fRAAA8w8e+v8lBi0AAGYPH0QAAPMPHvr/Jf4sAABmDx9EAADzDx76/yX2LAAAZg8fRAAA8w8e+v8l7iwAAGYPH0QAAPMPHvr/JeYsAABmDx9EAADzDx76/yXeLAAAZg8fRAAA8w8e+v8l1iwAAGYPH0QAAPMPHvpBV0FWQVVBVEmJ9FVTSIPseGRIiwQlKAAAAEiJRCRoMcCNR/6D+AEPhxMEAACJ+0iLfgi6CgAAADH26C3////zDxA9uQwAAEiJxfMPEXwkMIP7Aw+EDwQAAL4gAAAAvwEAAADoRP///zH/SI1wEEmJx+iG/v//SYkHSInH6Dv+//9BicWFwA+FEgQAAEmLPzHbTI1kJFDoof7//0iJx+h5/v//QYN/EABIiUQkUEiJVCRYfhkPH4QAAAAAAEyJ54PDAegF////QTtfEHzvSItEJFBJiz9JiUcIizDozP3//0mLPzHSicboYP7//0mJxkiFwA+EjwMAAEiJx+hc/v//TIn3icPowv3//0hj00iNPNUAAAAASIkUJEmJxOjL/f//MfaF20iLFCRJiUcYQYl3FH5lSY0clA8fRAAAQYs0JEmLP+hE/v//SYs/MdKJxui4/f//SInHSIXAdC4Pt0AIZoXAdCVBi08UZkEPbgQkZg9u8EmLRxhIicpmD2LGg8IBZg/WBMhBiVcU6J39//9Jg8QETDnjdaRMiffojP3//0GDfxQAD4QXAgAAjYUY/P//uWQAAACJbCQ0mUSJbCRM9/mNBECNSAKNUAFImIlMJEgxyUiJRCQ4SGPCSIlMJBhIiUQkQA8fgAAAAABJi0cYSItMJBhIjQTISIlEJCCLRCQ0PYQDAAAPjucBAAA9C2IAAA+P+QEAAEiLTCQ4SI0FGAsAAEhjVCRI8w8QPIhIi0wkQPMPEXwkDPMPEDSI8w8QPJDzDxF0JBDzDxF8JBRIi0QkIESLaARPjWQtAESJLCRMiefog/z//0yJ50iJw+h4/P//TInnSInF6G38//+LFCRJicSF0g+E0gAAAI1C/2YP7/+JVCQsRTH280gPKvjzDxAFWAoAAA8oyPMPXkwkMPMPEXwkKA8fRAAARInyZg/vwPMPEUwkCPNIDyrC8w9eRCQo8w8RBCTzD1lEJAzouPv///MPWQUgCgAA8w8QTCQI8w8s0PMPEAQk8w9ZRCQQZkKJFHPokfv///MPWQX5CQAA8w8QTCQI8w8s0PMPEAQk8w9ZRCQU8w8RDCRmQolUdQDoZPv///MPWQXMCQAA8w8QDCTzDyzQZkOJFHRJg8YBTTnuD4Vh////i1QkLEiLRCQgSYs/D7fSTYnhSYnoSInZizDoIvz//0mLP4nG6Dj8//9Iid9JicXonfv//0iJ7+iV+///TInn6I37//9Nhe0PhekAAABIg0QkGAFIi0QkGEE7RxQPgi/+//9Ei2wkTEyJ/+jiAQAASItEJGhkSCsEJSgAAAAPhcoAAABIg8R4RInoW11BXEFdQV5BX8MPH0AAx0QkFAAAAADHRCQQrxY6PsdEJAwAAIA/6T7+///zDxA16wgAAPMPED3fCAAA8w8RdCQU8w8QNdkIAADzDxF8JBDzDxF0JAzpD/7//0iLDkiLPdIoAAC+AgAAADHASI0VuAgAAOh/+v//Qb0BAAAA6WL///9Ji3wkEDH26Hj7//9mD+//8g9a+PMPEXwkMOnS+///TIn/6B0BAADrzEyJ7+iT+v//6Qr///9Mif/ohvr//+u16M/6//9mLg8fhAAAAAAADx9EAADzDx76Me1JidFeSIniSIPk8FBURTHAMclIjT0h+////xUTKAAA9GYuDx+EAAAAAABIjT0ZKAAASI0FEigAAEg5+HQVSIsF1icAAEiFwHQJ/+APH4AAAAAAww8fgAAAAABIjT3pJwAASI014icAAEgp/kiJ8EjB7j9IwfgDSAHGSNH+dBRIiwWdJwAASIXAdAj/4GYPH0QAAMMPH4AAAAAA8w8e+oA9vScAAAB1K1VIgz16JwAAAEiJ5XQMSIs9hicAAOgJ+f//6GT////GBZUnAAABXcMPHwDDDx+AAAAAAPMPHvrpd////w8fgAAAAABTSIn7SIt/GEiF/3QF6G75//9IiztIhf90BegR+v//SInfW+lY+f//8w8e+kiD7AhIg8QIwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAIAAACAP5pUZT9jHR4/AP9/R1VzYWdlOiAlcyA8dGVtcD4gW2dhbW1hXQoAAAAAAAAAAAAAAAAAAAAAAAAAAACAP68WOj4AAAAAAACAP5qIZT4AAAAAAACAP51shD4AAAAAAACAP1Nekz4AAAAAAACAPzJkoD4AAAAAAACAP7/7qz4AAAAAAACAP/93tj4AAAAAAACAP1UQwD4AAAAAAACAPzvtyD4AAAAAAACAP7ks0T4AAAAAAACAPyrm2D4AAAAAAACAP0Ys4D4AAAAAAACAPy0O5z4AAAAAAACAP12Y7T4AAAAAAACAP9LU8z4AAAAAAACAP4zL+T4AAAAAAACAP9WC/z4AAAAAAACAP+F/Aj8AAAAAAACAP0QjBT8AAAAAAACAP1itBz8AAAAAAACAP6cfCj8AAAAAAACAP4l7DD8AAAAAAACAPzXCDj8AAAAAAACAP8f0ED8AAAAAAACAP0UUEz8AAAAAAACAP58hFT8AAAAAAACAP7MdFz8AAAAAAACAP20JGT8AAAAAAACAP5LlGj8AAAAAAACAP9eyHD8AAAAAAACAP95xHj8AAAAAAACAPzsjID8AAAAAAACAP3zHIT8AAAAAAACAPyNfIz8AAAAAAACAP6HqJD8AAAAAAACAP1ZqJj8AAAAAAACAP6LeJz8AAAAAAACAP9FHKT8AAAAAAACAPzGmKj8AAAAAAACAP/75Kz8AAAAAAACAP25DLT8AAAAAAACAP6uCLj8AAAAAAACAP+q3Lz8AAAAAAACAP1fjMD8AAAAAAACAPxkFMj8AAAAAAACAP2AdMz8AAAAAAACAP2UsND8AAAAAAACAP2IyNT8AAAAAAACAP44vNj8AAAAAAACAPxokNz8AAAAAAACAPzcQOD8AAAAAAACAPxP0OD8AAAAAAACAP9rPOT8AAAAAAACAP7SjOj8AAAAAAACAP8pvOz8AAAAAAACAP0I0PD8AAAAAAACAPz/xPD8AAAAAAACAP+OmPT8AAAAAAACAP05VPj8AAAAAAACAP578Pj8AAAAAAACAP/GcPz8AAAAAAACAP2U2QD8AAAAAAACAPxjJQD+XbQ45AACAP/djQT/zwiU6AACAP4X/QT9hi5s6AACAP7+bQj8n1us6AACAP6M4Qz8Z5iE7AACAPy7WQz+fu1E7AACAP110RD9XuII7AACAPy4TRT8RhZ47AACAP5+yRT+YRrw7AACAP6xSRj8v/9s7AACAP1PzRj9Gsf07AACAP5OURz+wrxA8AACAP2g2SD/MhSM8AACAP9DYSD84XDc8AACAP8p7ST8LNEw8AACAP1EfSj9zDmI8AACAP2bDSj+b7Hg8AACAPwRoSz/TZ4g8AACAPyoNTD9b3JQ8AACAP9ayTD921KE8AACAPwVZTT+wUK88AACAP7b/TT+VUb08AACAP+amTj+118s8AACAP5NOTz+W49o8AACAP7v2Tz+1deo8AACAP1ufUD+cjvo8AACAP3NIUT9nlwU9AACAPwDyUT9nKw49AACAPwCcUj+NAxc9AACAP3BGUz8bICA9AACAP1DxUz9RgSk9AACAP52cVD9nJzM9AACAP1ZIVT+bEj09AACAP3j0VT8lQ0c9AACAPwGhVj9DuVE9AACAP/BNVz8sdVw9AACAP0T7Vz8Yd2c9AACAP/qoWD9Av3I9AACAPxFXWT/WTX49AACAP4YFWj+JEYU9AACAP1m0Wj+TH4s9AACAP4hjWz8mUZE9AACAPxITXD9Vppc9AACAP/TCXD86H549AACAPy1zXT/vu6Q9AACAP70jXj+LfKs9AACAP6LUXj8kYbI9AACAP9qFXz/Uabk9AACAP2Q3YD+ulsA9AACAP0DpYD/N58c9AACAP2ubYT9EXc89X51/P488Yj/H4tY9E9J+P73RYj9uO949kgR+PyNmYz+9r+U95zR9P8T5Yz/gP+09GmN8P6KMZD8F7PQ9NY97P8AeZT9WtPw9QLl6PyCwZT+ATAI+ReF5P8VAZj8WTQY+TAd5P7HQZj8EXAo+XCt4P+dfZz9eeQ4+fk13P2nuZz86pRI+um12Pzt8aD+s3xY+F4x1P10JaT/JKBs+m6h0P9SVaT+ngB8+jsNzP/wgaj8A5CM+7N5yP9qqaj8bUSg+rPpxP3gzaz/mxyw+yRZxP9u6az9vSDE+RjNwPwdBbD/I0jU+JVBvPwHGbD//Zjo+Z21uP8tJbT8mBT8+D4ttP2vMbT9MrUM+HalsP+RNbj+CX0g+lMdrPzrObj/XG00+dOZqP3FNbz9d4lE+wAVqP4zLbz8ks1Y+eCVpP49IcD86jls+nkVoP33EcD+xc2A+NGZnP1s/cT+YY2U+OYdmPyy5cT/+XWo+sahlP/Mxcj/zYm8+m8pkP7Spcj+HcnQ++uxjP3Mgcz/IjHk+zg9jPzKWcz/GsX4+GTNiP/UKdD/I8IE+21ZhP79+dD8ajoQ+FntgP5TxdD/iMIc+zJ9fP3djdT8l2Yk+/MReP2rUdT/thow+qOpdP3JEdj8/Oo8+0RBdP5Czdj8j85E+eDdcP8khdz+isZQ+n15bPx+Pdz/AdZc+RYZaP5X7dz+HP5o+bK5ZPy5neD/8Dp0+FNdYP+zReD8n5J8+QABYP9Q7eT8Pv6I+7ylXP+ekeT+6n6U+IlRWPygNej8whqg+235VP5t0ej93cqs+GqpUP0Hbej+VZK4+4NVTPx9Bez+TXLE+LQJTPzWmez92WrQ+Cy9SP4AKfD/HXbc+2VxRP7VtfD8mZbo+fYtQP8/PfD/hcL0++bpPP9IwfT/+gMA+TetOP76QfT+BlcM+cBxOP5jvfT+ArsY+Y05NP2RNfj/9y8k+KIFMPyKqfj//7cw+v7RLP9YFfz+LFNA+KelKP4Jgfz+lP9M+ZR5KPym6fz9Ub9Y+lVlJPwAAgD/2jdk+p5BIPwAAgD8Mx9w+g8hHPwAAgD+3BOA+LAFHPwAAgD/6RuM+oDpGPwAAgD/bjeY+4HRFPwAAgD9e2ek+7a9EPwAAgD+JKe0+x+tDPwAAgD9hfvA+bihDPwAAgD/r1/M+4mVCPwAAgD8sNvc+JKRBPwAAgD8omfo+NONAPwAAgD/lAP4+EiNAPwAAgD+0tgA/v2M/PwAAgD9bbwI/OqU+PwAAgD9qKgQ/hOc9PwAAgD/k5wU/nSo9PwAAgD/Lpwc/hm48PwAAgD8iagk/P7M7PwAAgD/rLgs/yPg6PwAAgD8q9gw/IT86PwAAgD/fvw4/S4Y5PwAAgD8QjBA/Rc44PwAAgD+9WhI/ERc4PwAAgD/qKxQ/rmA3PwAAgD+Y/xU/HKs2PwAAgD/M1Rc/XPY1PwAAgD+Hrhk/bUI1PwAAgD/MiRs/UY80PwAAgD+eZx0/CN0zPwAAgD8ASB8/kCszPwAAgD/zKiE/7HoyPwAAgD97ECM/GssxPwAAgD+b+CQ/HBwxPwAAgD9U4yY/8W0wPwAAgD+r0Cg/mcAvPwAAgD+hwCo/FRQvPwAAgD86syw/ZWguPwAAgD94qC4/ir0tPwAAgD9doDA/ghMtPwAAgD/tmjI/T2osPwAAgD8qmDQ/8cErPwAAgD8YmDY/ZxorPwAAgD+4mjg/s3MqPwAAgD8OoDo/080pPwAAgD8cqDw/ySgpPwAAgD/lsj4/lYQoPwAAgD9twEA/NuEnPwAAgD+10EI/rT4nPwAAgD/B40Q/+pwmPwAAgD+T+UY/HvwlPwAAgD8uEkk/GFwlPwAAgD+VLUs/6LwkPwAAgD/LS00/jx4kPwAAgD/SbE8/DYEjPwAAgD+ukFE/Y+QiPwAAgD9it1M/j0giPwAAgD/v4FU/k60hPwAAgD9ZDVg/bxMhPwAAgD+jPFo/I3ogPwAAgD/Qblw/ruEfPwAAgD/jo14/EkofPwAAgD/e22A/TrMePwAAgD/FFmM/Yx0ePwAAgD+aVGU/UIgdPwAAgD9glWc/FvQcPwAAgD8a2Wk/tmAcPwAAgD/MH2w/Ls4bPwAAgD93aW4/gDwbPwAAgD8gtnA/q6saPwAAgD/JBXM/sRsaPwAAgD91WHU/j4wZPwAAgD8ornc/SP4YPwAAgD/jBno/3HAYPwAAgD+qYnw/SeQXPwAAgD+BwX4/3GAXPwAAgD8AAIA/e94WP17Gfz8AAIA/6VwWPxWNfz8AAIA/JNwVPyNUfz8AAIA/K1wVP4cbfz8AAIA//9wUP0Ljfj8AAIA/n14UP1Grfj8AAIA/CeETP7Zzfj8AAIA/PWQTP288fj8AAIA/OugSP3wFfj8AAIA/AG0SP93OfT8AAIA/jfIRP5KYfT8AAIA/4ngRP5lifT8AAIA//f8QP/MsfT8AAIA/3YcQP6D3fD8AAIA/gxAQP57CfD8AAIA/7ZkPP+2NfD8AAIA/GyQPP45ZfD8AAIA/DK8OP34lfD8AAIA/vzoOP8Dxez8AAIA/NMcNP1C+ez8AAIA/alQNPzGLez8AAIA/YeIMP2BYez8AAIA/F3EMP90lez8AAIA/jQAMP6nzej8AAIA/wZALP8PBej8AAIA/syELPyqQej8AAIA/Y7MKP95eej8AAIA/z0UKP94tej8AAIA/+NgJPyv9eT8AAIA/3GwJP8PMeT8AAIA/ewEJP6eceT8AAIA/1ZYIP9ZseT8AAIA/6CwIP1A9eT8AAIA/tcMHPxQOeT8AAIA/ARsDOzgAAAAGAAAAbOL//2wAAADc4///lAAAAOzj//+sAAAATOX//+AAAAAM6v//VAAAAPzq///EAAAAFAAAAAAAAAABelIAAXgQARsMBwiQAQAAFAAAABwAAACw6f//JgAAAABEBxAAAAAAJAAAADQAAAD44f//cAEAAAAOEEYOGEoPC3cIgAA/GjkqMyQiAAAAABQAAABcAAAAQOP//xAAAAAAAAAAAAAAABQAAAB0AAAAOOP//2ABAAAAAAAAAAAAABgAAACMAAAAMOr//ygAAAAAQQ4QgwJiDggAAABMAAAAqAAAAGTk//+xBAAAAEYOEI8CQg4YjgNCDiCNBEIOKIwFRA4whgZBDjiDB0QOsAED0QMKDjhEDjBBDihCDiBCDhhCDhBCDghFCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgGAAAAAAAAGAYAAAAAAAAAQAAAAAAAABIAgAAAAAAAAEAAAAAAAAAVAIAAAAAAAABAAAAAAAAAGYCAAAAAAAAAQAAAAAAAABwAgAAAAAAAAwAAAAAAAAAABAAAAAAAAANAAAAAAAAANgYAAAAAAAAGQAAAAAAAADgPAAAAAAAABsAAAAAAAAACAAAAAAAAAAaAAAAAAAAAOg8AAAAAAAAHAAAAAAAAAAIAAAAAAAAAPX+/28AAAAAsAMAAAAAAAAFAAAAAAAAAJAGAAAAAAAABgAAAAAAAADYAwAAAAAAAAoAAAAAAAAAsgIAAAAAAAALAAAAAAAAABgAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAED8AAAAAAAACAAAAAAAAABACAAAAAAAAFAAAAAAAAAAHAAAAAAAAABcAAAAAAAAAyAoAAAAAAAAHAAAAAAAAAPAJAAAAAAAACAAAAAAAAADYAAAAAAAAAAkAAAAAAAAAGAAAAAAAAAAeAAAAAAAAAAgAAAAAAAAA+///bwAAAAABAAAIAAAAAP7//28AAAAAgAkAAAAAAAD///9vAAAAAAIAAAAAAAAA8P//bwAAAABCCQAAAAAAAPn//28AAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAADAQAAAAAAAAQBAAAAAAAABQEAAAAAAAAGAQAAAAAAAAcBAAAAAAAACAEAAAAAAAAJAQAAAAAAAAoBAAAAAAAACwEAAAAAAAAMAQAAAAAAAA0BAAAAAAAADgEAAAAAAAAPAQAAAAAAAAABEAAAAAAAAQEQAAAAAAACARAAAAAAAAMBEAAAAAAABAEQAAAAAAAFARAAAAAAAAYBEAAAAAAABwEQAAAAAAAIARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAAAAAAABHQ0M6IChVYnVudHUgMTMuMy4wLTZ1YnVudHUyfjI0LjA0LjEpIDEzLjMuMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAABADx/wAAAAAAAAAAAAAAAAAAAAAJAAAAAQAEAIwDAAAAAAAAIAAAAAAAAAATAAAABADx/wAAAAAAAAAAAAAAAAAAAAAeAAAAAgAQALAYAAAAAAAAKAAAAAAAAAApAAAAAQASAEAgAAAAAAAAdA0AAAAAAAA5AAAABADx/wAAAAAAAAAAAAAAAAAAAABEAAAAAgAQAPAXAAAAAAAAAAAAAAAAAABGAAAAAgAQACAYAAAAAAAAAAAAAAAAAABZAAAAAgAQAGAYAAAAAAAAAAAAAAAAAABvAAAAAQAaAChAAAAAAAAAAQAAAAAAAAB7AAAAAQAWAOg8AAAAAAAAAAAAAAAAAACiAAAAAgAQAKAYAAAAAAAAAAAAAAAAAACuAAAAAQAVAOA8AAAAAAAAAAAAAAAAAAA5AAAABADx/wAAAAAAAAAAAAAAAAAAAADNAAAAAQAUAOQuAAAAAAAAAAAAAAAAAAAAAAAABADx/wAAAAAAAAAAAAAAAAAAAADbAAAAAAATALQtAAAAAAAAAAAAAAAAAADuAAAAAQAYABA/AAAAAAAAAAAAAAAAAAAEAQAAAQAXAPA8AAAAAAAAAAAAAAAAAABtAgAAIAAZAABAAAAAAAAAAAAAAAAAAAANAQAAEgAAAAAAAAAAAAAAAAAAAAAAAAAdAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABEAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABdAQAAEgAAAAAAAAAAAAAAAAAAAAAAAABxAgAAEgAQAMAXAAAAAAAAJgAAAAAAAACKAQAAEgAAAAAAAAAAAAAAAAAAAAAAAACkAQAAIAAAAAAAAAAAAAAAAAAAAAAAAACzAQAAEgIRANgYAAAAAAAAAAAAAAAAAAC5AQAAEgAAAAAAAAAAAAAAAAAAAAAAAADMAQAAEgAAAAAAAAAAAAAAAAAAAAAAAADYAQAAIAAAAAAAAAAAAAAAAAAAAAAAAAD0AQAAEgAAAAAAAAAAAAAAAAAAAAAAAAAYAgAAEQASAAAgAAAAAAAABAAAAAAAAAAnAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABAAgAAEgAAAAAAAAAAAAAAAAAAAAAAAABRAgAAIAAAAAAAAAAAAAAAAAAAAAAAAABrAgAAEAAZAABAAAAAAAAAAAAAAAAAAAB4AgAAIgAAAAAAAAAAAAAAAAAAAAAAAACTAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAChAgAAEgAAAAAAAAAAAAAAAAAAAAAAAADOAgAAEgAAAAAAAAAAAAAAAAAAAAAAAAACAwAAEQIZABBAAAAAAAAAAAAAAAAAAAAOAwAAEQIZAAhAAAAAAAAAAAAAAAAAAAAbAwAAEgAAAAAAAAAAAAAAAAAAAAAAAAAuAwAAEAAaACBAAAAAAAAAAAAAAAAAAAA6AwAAEgAAAAAAAAAAAAAAAAAAAAAAAABVAwAAEgAAAAAAAAAAAAAAAAAAAAAAAABzAwAAEgAAAAAAAAAAAAAAAAAAAAAAAACUAwAAEgAAAAAAAAAAAAAAAAAAAAAAAACnAwAAEAAaADBAAAAAAAAAAAAAAAAAAACsAwAAEgAAAAAAAAAAAAAAAAAAAAAAAAC+AwAAEQAaACBAAAAAAAAACAAAAAAAAADRAwAAEgAAAAAAAAAAAAAAAAAAAAAAAADhAwAAEgAAAAAAAAAAAAAAAAAAAAAAAADwAwAAEAAZABBAAAAAAAAAAAAAAAAAAAD3AwAAEgAAAAAAAAAAAAAAAAAAAAAAAAAUBAAAEgAAAAAAAAAAAAAAAAAAAAAAAAAnBAAAEgAQAAATAAAAAAAAsQQAAAAAAAAsBAAAEgIMAAAQAAAAAAAAAAAAAAAAAAAAU2NydDEubwBfX2FiaV90YWcAZy1lbmdpbmUuYwByYW5kcl9mcmVlAGJsYWNrYm9keV9jb2xvcgBjcnRzdHVmZi5jAGRlcmVnaXN0ZXJfdG1fY2xvbmVzAF9fZG9fZ2xvYmFsX2R0b3JzX2F1eABjb21wbGV0ZWQuMABfX2RvX2dsb2JhbF9kdG9yc19hdXhfZmluaV9hcnJheV9lbnRyeQBmcmFtZV9kdW1teQBfX2ZyYW1lX2R1bW15X2luaXRfYXJyYXlfZW50cnkAX19GUkFNRV9FTkRfXwBfX0dOVV9FSF9GUkFNRV9IRFIAX0dMT0JBTF9PRkZTRVRfVEFCTEVfAF9EWU5BTUlDAHBvd2ZAR0xJQkNfMi4yNwB4Y2JfcmFuZHJfZ2V0X3NjcmVlbl9yZXNvdXJjZXNfY3VycmVudAB4Y2JfY29ubmVjdGlvbl9oYXNfZXJyb3IAeGNiX3JhbmRyX2dldF9zY3JlZW5fcmVzb3VyY2VzX2N1cnJlbnRfY3J0Y3MAX19mcHJpbnRmX2Noa0BHTElCQ18yLjMuNABfX2dtb25fc3RhcnRfXwBfZmluaQBtYWxsb2NAR0xJQkNfMi4yLjUAeGNiX2Nvbm5lY3QAX0lUTV9kZXJlZ2lzdGVyVE1DbG9uZVRhYmxlAHhjYl9yYW5kcl9nZXRfY3J0Y19nYW1tYV9zaXplX3JlcGx5AF9JT19zdGRpbl91c2VkAHhjYl9zZXR1cF9yb290c19pdGVyYXRvcgBmcmVlQEdMSUJDXzIuMi41AF9JVE1fcmVnaXN0ZXJUTUNsb25lVGFibGUAX19kYXRhX3N0YXJ0AF9fY3hhX2ZpbmFsaXplQEdMSUJDXzIuMi41AHhjYl9nZXRfc2V0dXAAeGNiX3JhbmRyX2dldF9zY3JlZW5fcmVzb3VyY2VzX2N1cnJlbnRfcmVwbHkAeGNiX3JhbmRyX2dldF9zY3JlZW5fcmVzb3VyY2VzX2N1cnJlbnRfY3J0Y3NfbGVuZ3RoAF9fVE1DX0VORF9fAF9fZHNvX2hhbmRsZQBzdHJ0b2xAR0xJQkNfMi4yLjUAX19ic3Nfc3RhcnQAX19zdGFja19jaGtfZmFpbEBHTElCQ18yLjQAeGNiX3JhbmRyX2dldF9jcnRjX2dhbW1hX3NpemUAeGNiX3JhbmRyX3NldF9jcnRjX2dhbW1hX2NoZWNrZWQAY2FsbG9jQEdMSUJDXzIuMi41AF9lbmQAeGNiX3JlcXVlc3RfY2hlY2sAc3RkZXJyQEdMSUJDXzIuMi41AHhjYl9zY3JlZW5fbmV4dAB4Y2JfZGlzY29ubmVjdABfZWRhdGEAX19saWJjX3N0YXJ0X21haW5AR0xJQkNfMi4zNABzdHJ0b2RAR0xJQkNfMi4yLjUAbWFpbgBfaW5pdAAALnN5bXRhYgAuc3RydGFiAC5zaHN0cnRhYgAuaW50ZXJwAC5ub3RlLmdudS5wcm9wZXJ0eQAubm90ZS5nbnUuYnVpbGQtaWQALm5vdGUuQUJJLXRhZwAuZ251Lmhhc2gALmR5bnN5bQAuZHluc3RyAC5nbnUudmVyc2lvbgAuZ251LnZlcnNpb25fcgAucmVsYS5keW4ALnJlbGEucGx0AC5pbml0AC5wbHQuZ290AC5wbHQuc2VjAC50ZXh0AC5maW5pAC5yb2RhdGEALmVoX2ZyYW1lX2hkcgAuZWhfZnJhbWUALmluaXRfYXJyYXkALmZpbmlfYXJyYXkALmR5bmFtaWMALmRhdGEALmJzcwAuY29tbWVudAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAAABAAAAAgAAAAAAAAAYAwAAAAAAABgDAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAjAAAABwAAAAIAAAAAAAAAOAMAAAAAAAA4AwAAAAAAADAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAANgAAAAcAAAACAAAAAAAAAGgDAAAAAAAAaAMAAAAAAAAkAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAEkAAAAHAAAAAgAAAAAAAACMAwAAAAAAAIwDAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABXAAAA9v//bwIAAAAAAAAAsAMAAAAAAACwAwAAAAAAACgAAAAAAAAABgAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAYQAAAAsAAAACAAAAAAAAANgDAAAAAAAA2AMAAAAAAAC4AgAAAAAAAAcAAAABAAAACAAAAAAAAAAYAAAAAAAAAGkAAAADAAAAAgAAAAAAAACQBgAAAAAAAJAGAAAAAAAAsgIAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABxAAAA////bwIAAAAAAAAAQgkAAAAAAABCCQAAAAAAADoAAAAAAAAABgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAfgAAAP7//28CAAAAAAAAAIAJAAAAAAAAgAkAAAAAAABwAAAAAAAAAAcAAAACAAAACAAAAAAAAAAAAAAAAAAAAI0AAAAEAAAAAgAAAAAAAADwCQAAAAAAAPAJAAAAAAAA2AAAAAAAAAAGAAAAAAAAAAgAAAAAAAAAGAAAAAAAAACXAAAABAAAAEIAAAAAAAAAyAoAAAAAAADICgAAAAAAABACAAAAAAAABgAAABgAAAAIAAAAAAAAABgAAAAAAAAAoQAAAAEAAAAGAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAbAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAJwAAAABAAAABgAAAAAAAAAgEAAAAAAAACAQAAAAAAAAcAEAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAACnAAAAAQAAAAYAAAAAAAAAkBEAAAAAAACQEQAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAsAAAAAEAAAAGAAAAAAAAAKARAAAAAAAAoBEAAAAAAABgAQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAALkAAAABAAAABgAAAAAAAAAAEwAAAAAAAAATAAAAAAAA2AUAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAC/AAAAAQAAAAYAAAAAAAAA2BgAAAAAAADYGAAAAAAAAA0AAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAxQAAAAEAAAACAAAAAAAAAAAgAAAAAAAAACAAAAAAAAC0DQAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAM0AAAABAAAAAgAAAAAAAAC0LQAAAAAAALQtAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADbAAAAAQAAAAIAAAAAAAAA8C0AAAAAAADwLQAAAAAAAPgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA5QAAAA4AAAADAAAAAAAAAOA8AAAAAAAA4DwAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAPEAAAAPAAAAAwAAAAAAAADoPAAAAAAAAOg8AAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAD9AAAABgAAAAMAAAAAAAAA8DwAAAAAAADwPAAAAAAAACACAAAAAAAABwAAAAAAAAAIAAAAAAAAABAAAAAAAAAAqwAAAAEAAAADAAAAAAAAABA/AAAAAAAAED8AAAAAAADwAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAYBAAABAAAAAwAAAAAAAAAAQAAAAAAAAABAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAQAACAAAAAMAAAAAAAAAIEAAAAAAAAAQQAAAAAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAEQEAAAEAAAAwAAAAAAAAAAAAAAAAAAAAEEAAAAAAAAAtAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAoAUAAAAAAAAdAAAAFAAAAAgAAAAAAAAAGAAAAAAAAAAJAAAAAwAAAAAAAAAAAAAAAAAAAAAAAADgRQAAAAAAADIEAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAEQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAEkoAAAAAAAAaAQAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA=="

DATA_DIR   = os.path.expanduser("~/.local/share/gamma-slider")
CONFIG_DIR = os.path.expanduser("~/.config/gamma-slider")

G_ENGINE       = os.path.join(DATA_DIR,   "gamma-engine")
LOG_FILE       = os.path.join(DATA_DIR,   "gamma_slider.log")
CONFIG_FILE    = os.path.join(CONFIG_DIR, "gamma_slider.conf")
AUTOSTART_FILE = os.path.expanduser("~/.config/autostart/gamma_slider.desktop")
MENU_FILE      = os.path.expanduser("~/.local/share/applications/gamma_slider.desktop")

os.makedirs(DATA_DIR,   exist_ok=True)
os.makedirs(CONFIG_DIR, exist_ok=True)

_handler = RotatingFileHandler(LOG_FILE, maxBytes=1 * 1024 * 1024, backupCount=2)
_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s",
                                        datefmt="%Y-%m-%d %H:%M:%S"))
log = logging.getLogger("gamma_slider")
log.setLevel(logging.INFO)
log.addHandler(_handler)

# ---------------------------------------------------------------------------

LANGUAGES = {
    "en": {"name": "English",   "active": "Enabled",    "title": "Color Temp",     "show_label": "Tray Value",   "auto": "Auto",      "contrast": "Visibility", "quit": "Exit",    "as_on": "Autostart: ON",         "as_off": "Autostart: OFF"},
    "ru": {"name": "Русский",   "active": "Включено",   "title": "Температура",    "show_label": "В трее",       "auto": "Авто",      "contrast": "Видимость",  "quit": "Выход",   "as_on": "Автозапуск: ВКЛ",       "as_off": "Автозапуск: ВЫКЛ"},
    "zh": {"name": "中文",       "active": "已启用",      "title": "色温",           "show_label": "托盘数值",      "auto": "自动",      "contrast": "可见性",      "quit": "退出",    "as_on": "自启动: 开启",           "as_off": "自启动: 关闭"},
    "es": {"name": "Español",   "active": "Activado",   "title": "Temp. de color", "show_label": "En bandeja",   "auto": "Auto",      "contrast": "Visibilidad","quit": "Salir",   "as_on": "Inicio auto: ON",        "as_off": "Inicio auto: OFF"},
    "hi": {"name": "हिन्दी",    "active": "सक्रिय",     "title": "रंग तापमान",    "show_label": "ट्रे मान",    "auto": "ऑटो",      "contrast": "दृश्यता",   "quit": "निकास",  "as_on": "ऑटोस्टार्ट: चालू",     "as_off": "ऑटोस्टार्ट: बंद"},
    "ar": {"name": "العربية",   "active": "مفعل",       "title": "درجة الحرارة",   "show_label": "قيمة التبويب", "auto": "تلقائي",   "contrast": "الرؤية",    "quit": "خروج",   "as_on": "بدء تلقائي: تشغيل",    "as_off": "بدء تلقائي: إيقاف"},
    "pt": {"name": "Português", "active": "Ativado",    "title": "Temp. Cor",      "show_label": "Na bandeja",   "auto": "Auto",      "contrast": "Visibilidade","quit": "Sair",   "as_on": "Auto-início: LIG",       "as_off": "Auto-início: DES"},
    "fr": {"name": "Français",  "active": "Activé",     "title": "Temp. Couleur",  "show_label": "Dans le tray", "auto": "Auto",      "contrast": "Visibilité", "quit": "Quitter", "as_on": "Démarrage: ON",          "as_off": "Démarrage: OFF"},
    "de": {"name": "Deutsch",   "active": "Aktiviert",  "title": "Farbtemp.",      "show_label": "Tray-Wert",    "auto": "Auto",      "contrast": "Sichtbarkeit","quit": "Beenden","as_on": "Autostart: AN",           "as_off": "Autostart: AUS"},
    "ja": {"name": "日本語",     "active": "有効",        "title": "色温度",         "show_label": "トレイ表示",    "auto": "自動",      "contrast": "視認性",     "quit": "終了",    "as_on": "自動起動: オン",         "as_off": "自動起動: オフ"},
    "ko": {"name": "한국어",     "active": "활성화됨",    "title": "색온도",          "show_label": "트레이 값",    "auto": "자동",      "contrast": "시인성",     "quit": "종료",    "as_on": "자동 시작: 켜짐",        "as_off": "자동 시작: 꺼짐"},
    "he": {"name": "עברית",     "active": "פעיל",       "title": "טמפ' צבע",       "show_label": "ערך במגש",    "auto": "אוטומטי",  "contrast": "נראות",     "quit": "יציאה",  "as_on": "הפעלה אוטומטית: פעיל", "as_off": "הפעלה אוטומטית: כבוי"},
}
NAME_TO_CODE = {v["name"]: k for k, v in LANGUAGES.items()}

def target_temp_for_time(now: datetime) -> float:
    h = now.hour + now.minute / 60.0
    DAWN_START, DAWN_END  = 6.0,  7.5
    DUSK_START, DUSK_END  = 17.0, 21.0
    DAY_TEMP,   NIGHT_TEMP = 6500.0, 3000.0
    def lerp(a, b, t): return a + (b - a) * t
    if DAWN_START <= h < DAWN_END:
        return lerp(NIGHT_TEMP, DAY_TEMP, (h - DAWN_START) / (DAWN_END - DAWN_START))
    elif DAWN_END <= h < DUSK_START:
        return DAY_TEMP
    elif DUSK_START <= h < DUSK_END:
        return lerp(DAY_TEMP, NIGHT_TEMP, (h - DUSK_START) / (DUSK_END - DUSK_START))
    else:
        return NIGHT_TEMP

SMOOTH_STEP     = 100   
SMOOTH_INTERVAL = 5000 
# ---------------------------------------------------------------------------

BUTTON1_MASK = 1 << 8


class X11Pointer:
    def __init__(self):
        self.display = None
        self.x11 = None
        if os.environ.get("XDG_SESSION_TYPE", "").lower() == "wayland":
            return

        lib_name = ctypes.util.find_library("X11")
        if not lib_name:
            log.warning("libX11 not found; outside-click polling is unavailable")
            return

        try:
            self.x11 = ctypes.cdll.LoadLibrary(lib_name)
            self.x11.XOpenDisplay.argtypes = [ctypes.c_char_p]
            self.x11.XOpenDisplay.restype = ctypes.c_void_p
            self.x11.XDefaultRootWindow.argtypes = [ctypes.c_void_p]
            self.x11.XDefaultRootWindow.restype = ctypes.c_ulong
            self.x11.XQueryPointer.argtypes = [
                ctypes.c_void_p, ctypes.c_ulong,
                ctypes.POINTER(ctypes.c_ulong), ctypes.POINTER(ctypes.c_ulong),
                ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int),
                ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int),
                ctypes.POINTER(ctypes.c_uint)
            ]
            self.x11.XQueryPointer.restype = ctypes.c_int
            self.display = self.x11.XOpenDisplay(None)
            if not self.display:
                log.warning("XOpenDisplay failed; outside-click polling is unavailable")
        except Exception as e:
            log.warning(f"X11 pointer init failed: {e}")
            self.display = None
            self.x11 = None

    def state(self):
        if not self.display or not self.x11:
            return None

        root = self.x11.XDefaultRootWindow(self.display)
        root_return = ctypes.c_ulong()
        child_return = ctypes.c_ulong()
        root_x = ctypes.c_int()
        root_y = ctypes.c_int()
        win_x = ctypes.c_int()
        win_y = ctypes.c_int()
        mask = ctypes.c_uint()

        ok = self.x11.XQueryPointer(
            self.display, root,
            ctypes.byref(root_return), ctypes.byref(child_return),
            ctypes.byref(root_x), ctypes.byref(root_y),
            ctypes.byref(win_x), ctypes.byref(win_y),
            ctypes.byref(mask)
        )
        if not ok:
            return None

        return root_x.value, root_y.value, mask.value

def save_settings(s):
    try:
        with open(CONFIG_FILE, "w") as f:
            for k, v in s.items(): f.write(f"{k}={v}\n")
    except Exception as e:
        log.error(f"save_settings: {e}")

def load_settings():
    s = {"temp": 6500, "show_label": 0, "lang": "ru", "auto": 0, "contrast": 0, "enabled": 1}
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r") as f:
                for line in f:
                    if "=" in line:
                        k, v = line.strip().split("=", 1)
                        s[k.strip()] = int(v.strip()) if v.strip().isdigit() else v.strip()
        except Exception as e:
            log.error(f"load_settings: {e}")
    return s

def unpack_engine():
    if not ENGINE_B64: return
    try:
        bin_data = base64.b64decode(ENGINE_B64)
        if not os.path.exists(G_ENGINE):
            with open(G_ENGINE, "wb") as f: f.write(bin_data)
            os.chmod(G_ENGINE, 0o755)
            log.info(f"Engine unpacked to {G_ENGINE}")
    except Exception as e:
        log.error(f"unpack_engine: {e}")

def reset_gamma():
    if os.path.exists(G_ENGINE):
        try:
            subprocess.run([G_ENGINE, "6500", "1.0"],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            log.info("Gamma reset")
        except Exception as e:
            log.error(f"reset_gamma: {e}")

# ---------------------------------------------------------------------------

class JumpSlider(QSlider):
    def mousePressEvent(self, event):
        if self.isEnabled() and event.button() == _LEFT_BUTTON:
            val = self.minimum() + ((self.maximum() - self.minimum()) * event.pos().x()) / self.width()
            self.setValue(int(val))
        super().mousePressEvent(event)

    def wheelEvent(self, event):
        if not self.isEnabled(): return
        delta = 100 if event.angleDelta().y() > 0 else -100
        self.setValue(max(self.minimum(), min(self.maximum(), self.value() + delta)))


class PopupSlider(QWidget):
    def __init__(self, settings, tray_parent):
        super().__init__()
        self.tray_parent = tray_parent
        self.s = settings
        self._float_temp = float(self.s['temp'])

        self.setWindowFlags(_POPUP | _FRAMELESS | _STAYS_ON_TOP)
        self.setFixedSize(320, 200)
        self.setStyleSheet("""
            QWidget { background-color: #1e1e1e; color: #ffffff; border: 1px solid #444; border-radius: 8px; }
            QSlider::groove:horizontal {
                height: 8px; border-radius: 4px;
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ff3300, stop:0.5 #ffffff, stop:1 #3399ff);
            }
            QSlider::handle:horizontal { background: #ffffff; border: 2px solid #000; width: 18px; height: 18px; margin: -5px 0; border-radius: 9px; }
            QPushButton { background: #333; padding: 5px; border-radius: 4px; }
            QPushButton:hover { background: #444; }
            QComboBox { background: #333; }
        """)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(15, 10, 15, 10)

        top = QHBoxLayout()
        self.check_enabled = QCheckBox()
        self.check_enabled.setChecked(bool(self.s['enabled']))
        self.check_enabled.setStyleSheet("font-size: 13px; color: #fb923c; font-weight: bold;")
        self.check_enabled.stateChanged.connect(self.toggle_power)
        self.title_label = QLabel()
        self.title_label.setFont(QFont("Verdana", 10, _BOLD))
        self.title_label.setStyleSheet("border: none;")
        top.addWidget(self.check_enabled); top.addStretch(); top.addWidget(self.title_label)
        layout.addLayout(top)

        self.slider = JumpSlider(_HORIZONTAL)
        self.slider.setRange(1000, 10000)
        self.slider.setValue(int(self.s['temp']))
        self.slider.valueChanged.connect(self.sync)
        layout.addWidget(self.slider)

        mid = QHBoxLayout()
        self.check_label = QCheckBox()
        self.check_label.setChecked(bool(self.s['show_label']))
        self.check_label.stateChanged.connect(self.sync)
        self.check_auto = QCheckBox()
        self.check_auto.setChecked(bool(self.s['auto']))
        self.check_auto.stateChanged.connect(self.toggle_auto)
        mid.addWidget(self.check_label); mid.addStretch(); mid.addWidget(self.check_auto)
        layout.addLayout(mid)

        bot = QHBoxLayout()
        self.check_contrast = QCheckBox()
        self.check_contrast.setChecked(bool(self.s['contrast']))
        self.check_contrast.stateChanged.connect(self.sync)
        self.lang_box = QComboBox()
        self.lang_box.addItems([LANGUAGES[k]["name"] for k in LANGUAGES])
        self.lang_box.setCurrentText(LANGUAGES.get(self.s['lang'], LANGUAGES['ru'])["name"])
        self.lang_box.currentTextChanged.connect(self.change_lang)
        bot.addWidget(self.check_contrast); bot.addStretch(); bot.addWidget(self.lang_box)
        layout.addLayout(bot)

        self.btn_as = QPushButton()
        self.btn_as.clicked.connect(self.toggle_as)
        layout.addWidget(self.btn_as)

        self.smooth_timer = QTimer()
        self.smooth_timer.timeout.connect(self._smooth_tick)
        self.smooth_timer.start(SMOOTH_INTERVAL)

        self.outside_click_timer = QTimer()
        self.outside_click_timer.setInterval(30)
        self.outside_click_timer.timeout.connect(self._watch_outside_click)
        self._wait_for_mouse_release = False
        self._pending_outside_click = False
        self._ignore_outside_click_until = 0.0
        self._suppress_tray_show_until = 0.0
        self.x11_pointer = X11Pointer()

        self.retranslate_ui()
        self.tray_parent.update_icon(self._display_temp(), self.s['show_label'])
        QTimer.singleShot(500, self.sync)

        QApplication.instance().installEventFilter(self)

        # Wayland warning + disable controls (X11-only app)
        if os.environ.get("XDG_SESSION_TYPE", "").lower() == "wayland":
            warning_label = QLabel("⚠ Wayland detected — this app requires an X11 session.\nGamma changes will not work.")
            warning_label.setStyleSheet("color: #ff6b6b; font-weight: bold; font-size: 11px; padding: 8px; background: #331111; border-radius: 4px;")
            warning_label.setWordWrap(True)
            self.layout().insertWidget(0, warning_label)

            for wtype in (QSlider, QPushButton, QCheckBox, QComboBox):
                for widget in self.findChildren(wtype):
                    widget.setEnabled(False)

    def _display_temp(self) -> int:
        return round(self._float_temp / 100) * 100

    def _smooth_tick(self):
        if not self.s.get('auto') or not self.s.get('enabled'):
            return
        target  = target_temp_for_time(datetime.now())
        current = self._float_temp
        if abs(current - target) < 1:
            return
        step      = SMOOTH_STEP if target > current else -SMOOTH_STEP
        new_float = current + step
        if (step > 0 and new_float > target) or (step < 0 and new_float < target):
            new_float = target
        self._float_temp = new_float
        disp = self._display_temp()
        self.s['temp'] = disp
        self.apply_engine(disp)
        self.tray_parent.update_icon(disp, self.s['show_label'])
        self.title_label.setText(
            f"{LANGUAGES.get(self.s['lang'], LANGUAGES['ru'])['title']}: {disp} K"
        )
        log.info(f"Auto smooth: {round(current)}K → {disp}K (target {round(target)}K)")

    def retranslate_ui(self):
        l = LANGUAGES.get(self.s['lang'], LANGUAGES['ru'])
        self.check_enabled.setText(l['active'])
        self.check_label.setText(l['show_label'])
        self.check_auto.setText(l['auto'])
        self.check_contrast.setText(l['contrast'])
        self.btn_as.setText(l['as_on'] if os.path.exists(MENU_FILE) else l['as_off'])
        self.title_label.setText(f"{l['title']}: {self.s['temp']} K")
        is_act = self.check_enabled.isChecked() and not self.check_auto.isChecked()
        self.slider.setEnabled(is_act)
        self.check_contrast.setEnabled(is_act)

    def toggle_power(self, state):
        self.s['enabled'] = int(state)
        if not state: reset_gamma()
        else: self.sync()
        save_settings(self.s)
        self.retranslate_ui()

    def toggle_auto(self, state):
        self.s['auto'] = int(state)
        if state:
            log.info(f"Auto ON. current={self._display_temp()}K target={round(target_temp_for_time(datetime.now()))}K")
            self._smooth_tick()
        else:
            self.sync()
        save_settings(self.s)
        self.retranslate_ui()

    def change_lang(self, name):
        self.s['lang'] = NAME_TO_CODE.get(name, "ru")
        save_settings(self.s)
        self.retranslate_ui()
        self.tray_parent.update_menu()

    def sync(self):
        if self.s['auto'] and self.s['enabled']: return
        val = (self.slider.value() // 100) * 100
        self.s['temp']       = val
        self._float_temp     = float(val)
        self.s['show_label'] = int(self.check_label.isChecked())
        self.s['contrast']   = int(self.check_contrast.isChecked())
        if self.s['enabled']: self.apply_engine(val)
        self.tray_parent.update_icon(val, self.s['show_label'])
        self.title_label.setText(
            f"{LANGUAGES.get(self.s['lang'], LANGUAGES['ru'])['title']}: {val} K"
        )
        save_settings(self.s)

    def apply_engine(self, temp):
        if not os.path.exists(G_ENGINE):
            log.warning(f"Engine not found: {G_ENGINE}")
            return
        gamma = "1.3" if self.s.get('contrast', 0) else "1.0"
        try:
            subprocess.Popen([G_ENGINE, str(temp), gamma],
                             stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            log.debug(f"Engine: temp={temp}K gamma={gamma}")
        except Exception as e:
            log.error(f"apply_engine: {e}")

    def toggle_as(self):
        if os.path.exists(MENU_FILE):
            for p in [AUTOSTART_FILE, MENU_FILE]:
                if os.path.exists(p):
                    os.remove(p)
                    log.info(f"Autostart removed: {p}")
        else:
            p_bin = os.path.abspath(sys.argv[0])
            d = (f"[Desktop Entry]\nType=Application\nName=Gamma Slider\n"
                 f"Exec=python3 {p_bin}\nIcon=weather-clear\nCategories=Settings;\nTerminal=false\n")
            for p in [AUTOSTART_FILE, MENU_FILE]:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                with open(p, "w") as f: f.write(d)
            log.info("Autostart enabled")
        self.retranslate_ui()

    def showEvent(self, event):
        self._wait_for_mouse_release = True
        self._pending_outside_click = False
        self.outside_click_timer.start()
        super().showEvent(event)

    def hideEvent(self, event):
        self.outside_click_timer.stop()
        super().hideEvent(event)

    def show_at_cursor(self):
        pos = QCursor.pos()
        self.move(pos.x() - 160, pos.y() - 220)
        self.ignore_outside_clicks()
        self._show_and_raise()

    def bring_to_front(self):
        self._wait_for_mouse_release = True
        self.ignore_outside_clicks()
        self._show_and_raise()

    def ignore_outside_clicks(self, ms=350):
        self._pending_outside_click = False
        self._ignore_outside_click_until = time.monotonic() + (ms / 1000.0)

    def hide_from_tray(self):
        self._pending_outside_click = False
        self.hide()

    def should_suppress_tray_show(self):
        if time.monotonic() < self._suppress_tray_show_until:
            self._suppress_tray_show_until = 0.0
            return True
        return False

    def _show_and_raise(self):
        if not self.isVisible():
            self.show()
        self.raise_()
        self.activateWindow()
        self.outside_click_timer.start()

    def _watch_outside_click(self):
        x11_state = self.x11_pointer.state()
        if x11_state:
            _, _, mask = x11_state
            left_pressed = bool(mask & BUTTON1_MASK)
        else:
            buttons = QApplication.mouseButtons()
            left_pressed = bool(buttons & _LEFT_BUTTON)

        now = time.monotonic()
        outside = not self._contains_global_pos(QCursor.pos())

        if self._wait_for_mouse_release:
            if not left_pressed:
                self._wait_for_mouse_release = False
            return

        if now < self._ignore_outside_click_until:
            self._pending_outside_click = False
            return

        if left_pressed:
            self._pending_outside_click = outside
            return

        if self._pending_outside_click and outside:
            self._pending_outside_click = False
            self._suppress_tray_show_until = time.monotonic() + 0.35
            self.hide()
        else:
            self._pending_outside_click = False

    def _contains_global_pos(self, pos):
        widget = QApplication.widgetAt(pos)
        active_popup = QApplication.activePopupWidget()

        current = widget
        while current:
            if current is active_popup:
                return True
            current = current.parentWidget()

        current = widget
        while current:
            if current is self:
                return True
            if current.window() is self:
                return True
            current = current.parentWidget()

        top_left = self.mapToGlobal(self.rect().topLeft())
        bottom_right = self.mapToGlobal(self.rect().bottomRight())
        return top_left.x() <= pos.x() <= bottom_right.x() and top_left.y() <= pos.y() <= bottom_right.y()

    def eventFilter(self, obj, event):
        return super().eventFilter(obj, event)

class TrayApp(QObject):
    def __init__(self):
        super().__init__()
        self.app = QApplication(sys.argv)
        self.app.setQuitOnLastWindowClosed(False)
        self.app.aboutToQuit.connect(self.on_exit)

        self.settings = load_settings()
        unpack_engine()
        log.info(f"Gamma Slider started (PyQt{QT_VERSION})")

        self.tray = QSystemTrayIcon()
        self.menu = QMenu()
        self.tray.setContextMenu(self.menu)
        self.update_menu()

        self.update_icon(self.settings['temp'], self.settings['show_label'])

        self.popup = PopupSlider(self.settings, self)
        self.tray.activated.connect(self.clicked)
        self.tray.show()

    def on_exit(self):
        log.info("Exiting")
        reset_gamma()

    def update_menu(self):
        self.menu.clear()
        l = LANGUAGES.get(self.settings.get('lang', 'ru'), LANGUAGES['ru'])
        self.menu.addAction(l['quit']).triggered.connect(self.app.quit)

    def update_icon(self, val, show):
        pix = QPixmap(64, 64)
        pix.fill(_TRANSPARENT)
        p = QPainter(pix)
        p.setRenderHint(_ANTIALIAS)
        p.setBrush(QColor("#fb923c"))
        p.setPen(_NO_PEN)
        p.drawEllipse(4, 4, 56, 56)
        if show:
            p.setPen(QColor("black"))
            p.setFont(QFont("Verdana", 28, _BOLD))
            p.drawText(pix.rect(), _ALIGN_CENTER, str(val // 100))
        p.end()
        self.tray.setIcon(QIcon(pix))
        self.tray.setToolTip(f"{val} K")

    def clicked(self, r):
        if r == _TRAY_TRIGGER:
            if self.popup.isVisible():
                self.popup.hide_from_tray()
            elif not self.popup.should_suppress_tray_show():
                self.popup.show_at_cursor()

if __name__ == "__main__":
    lock = open('/tmp/gamma_slider.lock', 'w')
    try: fcntl.lockf(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except: sys.exit(0)
    app = TrayApp()
    sys.exit(app.app.exec())
